Create ifl floating window
SzatmariA/CharmFL-dev pull request #35
Opened 2022-10-27 07:47 UTC by SamuraiSnail

I have implemented the basic behaviour of the floating window. Now it is able to display the expected panels and calculate (and also display) scores based on some dummy data. The remaining work with it is to attach the real input and output, but in this state it is able to be presented (at least)

2022-10-27 07:50 UTC, SzatmariA requested changes

2022-10-27 07:50 UTC, SzatmariA commented on src/main/java/ui/ScoresFloatingWindow.java
> +        indicators.forEach((k,v)->mainPanel.add(v));
Do not use k and v, they are not really good names for variables

2022-10-27 07:50 UTC, SzatmariA commented on src/main/java/ui/ScorePanel.java
> +        for (int i = 1; i <= uLimit; i++) {
what is the uLimit?

2022-11-05 12:12 UTC, SzatmariA approved these changes

2022-11-05 12:13 UTC, SamuraiSnail commented
I have implemented the communication between the floating window and the data. Although currently this means that the indicators will update themselves based on the selected component. The other way is not implemented yet.

2022-11-05 12:26 UTC, merged